services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "pg_fin_analyst"
    volumes:
      - "fin_analyst_pg_data:/var/lib/postgresql"
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - "pg_admin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"

volumes:
  fin_analyst_pg_data:
  pg_admin_data:
